markdown: kramdown
excerpt_separator: ""

collections:
  docs:
    output: true
# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Purplebricks - Tech Blog
tagline: Keeping Purplebricks Moving

production_url : http://purplebricks.github.io
BASE_PATH : false
ASSET_PATH : false
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml
encoding: utf-8